### PR TITLE
Revert "Update parser value set types"

### PR DESCRIPTION
**Pull request by jnfoster**
Reverts p4lang/p4-spec#873

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
Why should we revert the value set types?

**Comment by apinski-cavium** [comment]
Yes I don't see why can't signed types be valid here? (the bitwise operators are valid for fixed signed integer types even).

For serializable enum case, should it decay to the underlying type instead or does it keep it as the enum type?

**Comment by jnfoster** [comment]
I'd merged this prematurely at the last LDWG...

**Comment by mbudiu-vmw** [comment]
Can we close this PR?

**Comment by mbudiu-vmw** [comment]
I think it's too late now to consider this, we should just close it.

**Pull request closed without merging**
