### PR TITLE
Explicitly disallow overloading parsers, controls, packages

### LINKED ISSUE #1055: Does parser overload check argument types
Take:
```
parser p( bit y ) {
    state start {
        transition accept;
    }
}

parser p(bit u, bit t) {
    state start {
        transition accept;
    }
}
parser p1(bit u, bit p2) {
    p() pp;
    state start {
        pp(u,p2);
        pp(u, 1);
        transition accept;
    }
}
```

The reference compiler errors out at the point of instantation:
```
t8.p4(13): [--Werror=duplicate] error: p: multiple matching declarations
    p() pp;
    ^
t8.p4(1): [--Werror=duplicate] error: Candidate: parser p
parser p( bit y ) {
       ^
t8.p4(7): [--Werror=duplicate] error: Candidate: parser p
parser p(bit u, bit t) {
       ^
```
I think it is right to do. The specification should be clarified to make this explictly invalid code. 

As an aside should it be at the point of definition rather than at the point of instantation?

### PR DESCRIPTION
**Pull request by mbudiu-vmw**
Signed-off-by: Mihai Budiu <mbudiu@vmware.com>

Fixes #1055

### CODE REVIEW

**Review by mbudiu-vmw — COMMENTED** [review]
In this example there are no constructor arguments at all, so overloading based on constructor arguments would not work.

**Comment by mbudiu-vmw** [comment]
@vgurevich do you know if there are examples of people overloading such constructs in real programs?

**Review by rst0git — APPROVED** [review]
LGTM

**Comment by jnfoster** [comment]
@mbudiu-vmw should we also add a ChangeLog for this?

**Pull request merged**
