### PR TITLE
Some spacing, capitalization, formatting, and oxford comma fixes

### PR DESCRIPTION
**Pull request by akeep**
**Spacing**

This pull request fixes some spacing (missing space between two sentences), changes references to 'run time' and 'run-time' to 'runtime' (even though I prefer the former) to be consistent with the common usage in the document.

**Capitalization**

Changed Header Union references to Header union to make it consistent with Header type and Header stack. Lower-cased Boolean to be consistent with uses of integer.  Changed one instance of Compile-Time to Compile-time to match the other reference.

**Formatting**

Fixed some formatting issues where comma grouped items were surrounded by \`\`\`, when I noticed it (e.g. \`\`\`in, inout\`\`\` and \`\`\`out\`\`\` becomes: \`\`\`in\`\`\`, \`\`\`inout\`\`\`, and \`\`\`out\`\`\` (with the added oxford comma).  Added '\#undef' and '\#line' to the directives list, so they would match '\#if', '\#include', etc. in the formatting.

**Oxford Commas**

Added oxford commas, where appropriate, to make the use consistent across the document.

### CODE REVIEW

**Comment by jnfoster** [comment]
Hi Andy,

Thanks for inputting these changes again. They look great. And sorry, other Andy's pull request got merged first and now this one has a conflict (this is one unlucky PR)! Would you like to detangle or should I?

**Comment by akeep** [comment]
I can detangle it.  I was sort of hanging out for a few minutes before going to bed to let his changes filter in to resolve any conflicts.

**Comment by jafingerhut** [comment]
Aw, George Boole will be so upset you are uncapitalizing his name! :-)  (I don't care much either way)

**Comment by jnfoster** [comment]
You know a document is nearing completion when you're arguing about hyphenation, capitalization, and Oxford commas with your collaborators...

**Comment by akeep** [comment]
Should be good to go.

**Comment by akeep** [comment]
Indeed :)

**Pull request merged**
