### PR TITLE
update text to allow annotation on extern methods and constructors

### PR DESCRIPTION
**Pull request by hanw**

### CODE REVIEW

**Comment by hanw** [comment]
Updated grammar.mdk.

**Comment by hanw** [comment]
Someone with write access has to merge this.

**Comment by jnfoster** [comment]
Just to clear on the process, by merging this, @mbudiu-vmw is classifying this as a technical bug fix that does not need to be escalated to the LDWG?

**Comment by mbudiu-vmw** [comment]
That's what it looks to me. It is not changing substantively anything in the language, just allowing annotations on a few more syntactic elements.

**Comment by jnfoster** [comment]
Sounds good. Can one of you drop a brief note to p4-design linking to this PR and notifying everyone of the change?

**Comment by hanw** [comment]
@mbudiu-vmw Can you send this email, please? I am not sure if I have permission to post on that email list.

**Pull request merged**
