### PR TITLE
Fix incorrect cross-reference label

### PR DESCRIPTION
**Pull request by jfingerh**

### CODE REVIEW

**Comment by jfingerh** [comment]
Starting from the latest main as of 2023-Apr-30, there is only 1 warning about invalid cross-references that I see when creating HTML and PDF versions of the spec, and this PR fixes that.

It also updates what I believe is the only occurrence of "infinite-precision integer" that has not yet been replaced with "arbitrary-precision integer"

**Comment by mbudiu-vmw** [comment]
In this document https://p4.org/p4-spec/docs/p4-16-working-draft.html you can search for `[#`.

**Comment by jfingerh** [comment]
With commit 2 of this PR, there are no more occurrences of `[#` in the HTML output.

**Review by mbudiu-vmw — APPROVED** [review]

**Comment by jnfoster** [comment]
Thanks @jfingerh!

**Pull request merged**
