### PR TITLE
Support for trailing commas

### PR DESCRIPTION
**Pull request by mbudiu-vmw**
Signed-off-by: Mihai Budiu <mbudiu@vmware.com>

### CODE REVIEW

**Comment by apinski-cavium** [comment]
+1 from me (already implemented this as extension [with a pedantic warning] in my front-end).

**Comment by smolkaj** [comment]
This is awesome :) Thanks for adding it!

**Review by jafingerhut — APPROVED** [review]
LGTM

**Comment by mbudiu-vmw** [comment]
Can we merge this PR?

**Comment by jnfoster** [comment]
Lets do it.

**Pull request merged**
