### PR TITLE
Allow direct invocation of generic controls/parsers 

### PR DESCRIPTION
**Pull request by mbudiu-vmw**
I could argue that this is a bug, but perhaps it should be discussed in the design working group.

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
Fixes #1068

**Comment by jnfoster** [comment]
Even for bug fixes, I think we should at least notify the LDWG in a meeting for something that is a material change like this.

**Comment by mbudiu-vmw** [comment]
This should add an example.

**Comment by mbudiu-vmw** [comment]
Have added an example, as suggested during LDWG meeting.

**Review by jnfoster — APPROVED** [review]

**Pull request merged**
