### PR TITLE
Fix and prettify references to compile-time size determination

### PR DESCRIPTION
**Pull request by jnfoster**
- Replaced `[#sec-determin]` with `(Section [#sec-determin])` globally
- Also, `sec-determin` doesn't exist. I think it should have been `sec-minsizeinbits`?

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
I just looked here recently https://p4.org/p4-spec/docs/p4-16-working-draft.html and noticed that there are a few more broken links, maybe you can take a look at all of them?

**Comment by mbudiu-vmw** [comment]
They show up as "#" in the text.

**Comment by jnfoster** [comment]
Yep, I was going to do that next. Just breaking things down into small pieces for easy review... though, maybe too small :-)

**Review by mbudiu-vmw — APPROVED** [review]
Looks good here, but should be tested by generating the markup.

**Pull request merged**
