### PR TITLE
P4_16 spec: Clarify behavior of reads/writes of fields in invalid hea…

### PR DESCRIPTION
**Pull request by jafingerhut**
…ders

This is intended to resolve issue #285

### CODE REVIEW

**Comment by vgurevich** [comment]
@jafingerhut ,

The wording about what happens when you write an invalid header field seem to be significantly different from what was discussed before. It's been a while and I can't find any "records of agreement", but I think that the last posting in #285 by @jnfoster  is what he wanted to discuss, but not that final resolution. 

I still believe that accessing a field in an invalid header should be similar to accessing a pointer that we know does point to the heap, but has not been officially returned to us by malloc(). That is: reads will succeed, but you do not know what they will return (we are in agreement here), while writes will succeed too, but you do not know where they will go, except that they will go into the heap (in this case headers/metadata) and not in .text/stack (i.e. not program code, not tables and not externs).

**Comment by jafingerhut** [comment]
One of the options that we discussed was that by default the behavior of writes to invalid header fields was safe, i.e. it didn't corrupt any currently-defined state of the program.

As an option, some implementations are expected to provide options to opt-in to the less safe behavior that you describe.  That is described in the last paragraph of the current proposed change in this pull request.

The current pull request doesn't define precisely what those less-safe options are, or how you would opt-in, e.g. it could be a command line option in your compiler (or the default behavior of your compiler), some kind of whole-program P4_16 annotation, etc.

**Comment by vgurevich** [comment]
@jafingerhut ,

We can certainly mandate safe behavior and make unsafe behavior optional. I did see it in your pull request. What I am afraid of is that the users of many practical (especially hardware) implementations will be forced to (almost always) specify this option, thus defeating our good intentions.

**Comment by jafingerhut** [comment]
I have made more commits to this PR, attempting to address comments made during the 2017-Nov-27 P4_16 language work group meeting.  Here are the notes I took during that meeting describing the suggested changes:

Add clarification that for fields with enum type, an unspecified value
might not be equal to _any_ of the enum values defined within the enum
declaration.  This may violate compiler assumptions in if-then-else or
select expressions intended to be exhaustive.
 
Make explicit that reading a header field could be in a header_union
or a header stack, in addition to the already-mentioned header type.
 
Perhaps: Add one example of a ternary field match in a table with all
bit positions wild-carded, as one way to ignore an unspecified value.
 
 
 
For a header union, specify that invalid header field write must not
change validity of any header_union members.
 
Remove the last added paragraph.  Add a paragraph near the beginning
of the specification, with wording similar to this:
    "It is understood that some implementations may be unable to
    implement the behavior defined here in all cases.  They should
    document where they deviate from this specification."
 
No objections to leaving the 'safe behavior' proposed in the pull
request as the default of the language spec.

**Comment by jnfoster** [comment]
I'm happy.

**Comment by jafingerhut** [comment]
@jnfoster - I saw email about a comment you made about a paragraph that was in my first proposed PR, but was removed in a later commit at the suggestion of the WG.  Hopefully you are able to see the latest proposed changes in Github without that paragraph.

**Comment by jnfoster** [comment]
Yes, I'm happy now. 

Thanks! (And sorry for accidentally closing the PR; best not to let absent minded professors around GitHub repos ;-)

**Comment by mbudiu-vmw** [comment]
Why haven't we already merged this?

**Comment by jnfoster** [comment]
Agree. This was discussed and approved by the LDWG.

**Pull request merged**
