### PR TITLE
Replace Madoko P4 language and PSA specs with Asciidoc

### PR DESCRIPTION
**Pull request by jafingerhut**

### CODE REVIEW

**Comment by jafingerhut** [comment]
@rcgoodfellow I used some `git format-patch ...`, text file editing, and `git am ...` sequence of steps to create this PR, which has proper DCO on all commits, including yours and Davide Scano's.  I did a 'diff -cr' between this one, and the one created by the original PR here: https://github.com/p4lang/p4-spec/pull/1317

They are both identical.

**Comment by jafingerhut** [comment]
This looks good to merge to me.  I am not an expert reviewer for the Github workflow changes, but I am assuming if any changes are needed there to tweak it, they can be done after this is merged in.

**Comment by rcgoodfellow** [comment]
@jafingerhut are you able to [enable workflows](https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/disabling-and-enabling-a-workflow#enabling-a-workflow) on this fork, so we can see if they run ok?

**Comment by jafingerhut** [comment]
I'm not experienced with Github actions, believe it or not.  Is this a page showing the results of running the workflow you are interested in on my forked repo, on branch `replace-madoko-spec-with-asciidoc-try3` ?

**Comment by rcgoodfellow** [comment]
Yup, that's the one. For some reason, it was not showing up in the checks list for me. But the artifacts look good!

**Review by rcgoodfellow — APPROVED** [review]

**Comment by jafingerhut** [comment]
@rcgoodfellow I know more approvers gives a warmer fuzzier feeling when merging, but I'm not sure how many others are interested in reviewing the details of these changes.  OK to merge and see what the fallout is?

**Comment by rcgoodfellow** [comment]
Yeah, I'm good with landing this and continuing to improve things as we move forward with asciidoc.

**Comment by jafingerhut** [comment]
Sorry for the trouble -- someone merged in the approved for loop addition to the main branch before we merged this one in.  I am closing this one because it now has a conflict.  I created a new PR with the merge of the for loop changes into the Madoko->AsciiDoc PR, mainly because I was worried I would mess up this PR if I tried doing it on this same branch.

https://github.com/p4lang/p4-spec/pull/1332

**Pull request closed without merging**
