### PR TITLE
Formatting fixes

### PR DESCRIPTION
**Pull request by mbudiu-vmw**
The pdf tables were rendered wrong without these fixes.

### CODE REVIEW

**Comment by jnfoster** [comment]
How so? I'm not sure what @jafingerhut intended, but this looks okay to me.

p4-spec-table

**Comment by jafingerhut** [comment]
@jnfoster I tried building with the current version, and with Mihai's proposed changes.  The PDF file generated looks the same for both, but the HTML looks better with these changes than without them. With them, the top border line of the table looks normal.  Without them, the top border line is incomplete.

**Comment by jnfoster** [comment]
Ahh, I'd only checked the PDF based on the commit comment.

**Comment by jafingerhut** [comment]
I don't know whether Mihai replaced "HTML" with "PDF" by accident in his comment, or perhaps he is getting different output than we are for the PDF.

**Pull request merged**
