### PR TITLE
const default default_action

### PR DESCRIPTION
**Pull request by mbudiu-vmw**
Signed-off-by: Mihai Budiu <mbudiu@vmware.com>

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
Fixes #1113

**Comment by mbudiu-vmw** [comment]
This is a very delicate change, because it can break user programs. We should think carefully what to do about it.
The alternative is to change the spec in a backwards-incompatible way... we'll have to break something one way or the other.

**Comment by mbudiu-vmw** [comment]
@jnfoster will submit a PR against the spec.

**Comment by mbudiu-vmw** [comment]
I have updated this PR as discussed during the last LDWG. We now specify that the compiler-inserted default action is not const.

**Review by jnfoster — APPROVED** [review]
Thanks for taking care of this. LGTM

**Pull request merged**
