### PR TITLE
v1.0.4

### PR DESCRIPTION
**Pull request by jnfoster**
Draft proposal for v1.0.4 maintenance release.

### CODE REVIEW

**Comment by jafingerhut** [comment]
Sorry for taking so long to get to this.  I see your fork of this repo here https://github.com/jnfoster/p4-spec

but I do not see any branch v1.0.4 in that repo.  How does this PR still exist with your proposed changes?

**Comment by jnfoster** [comment]
@jafingerhut Sorry about that. At some point I moved my fork to another place and started fresh, which lost all branches, including v.1.0.4. I just restored it.

**Comment by jafingerhut** [comment]
@jnfoster I get an error when trying to push an additional commit to the v1.0.4 branch of your repository jnfoster/p4-spec:
```
 git push jnfoster v1.0.4
Username for 'https://github.com': jafingerhut
Password for 'https://jafingerhut@github.com': 
remote: Permission to jnfoster/p4-spec.git denied to jafingerhut.
fatal: unable to access 'https://github.com/jnfoster/p4-spec/': The requested URL returned error: 403
```
The commit I was trying to push is on my copy of your v1.0.4 branch in my jafingerhut/p4-spec-1 fork here: https://github.com/jafingerhut/p4-spec-1/commit/97794ee5476a1b61c20d046c948a9e5082c0e279

**Comment by jnfoster** [comment]
@jafingerhut I see the issue. This PR is based on my repo named p4-spec-bkp, not p4-spec.

I just cherry-picked the changes from your branch.

**Comment by jnfoster** [comment]
Argh. I did not close this pull request. However, it appears my fork was detached in some GitHub sense by the operation that made p4-spec public.

In the interest of making progress, I'm going to make a new pull request and I'll link to this discussion so we have a record of it.

**Comment by jafingerhut** [comment]
Yep, I had the same 'private fork of p4lang/p4-spec became "detached" from it when the fork was changed from private to public' behavior that you observed.  Or at least that is how I interpreted the evidence I saw.

**Pull request closed without merging**
