### PR TITLE
Narrow the legal types that can be introduced by `type`

### LINKED ISSUE #1044: type keyword only applies to base types?
I didn't know if I should filed this as a specification bug or as a bug in the reference compiler but I think it is just a specification issue.
Take:
```
header t
{
 bit y;
}
type t tyu;
```
The specifications in section 7.5 there is no requirement for type keyword to only handle with a base type (or a type which is type or a base type) but the reference compiler rejects the code:
```
t2.p4(6): [--Werror=type-error] error: tyu: `type' can only be applied to base types
type t tyu;
       ^^^
```

### PR DESCRIPTION
**Pull request by mbudiu-vmw**
Signed-off-by: Mihai Budiu <mbudiu@vmware.com>
Fixes #1044 
To be discussed by the LDWG.

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
See also https://github.com/p4lang/p4c/pull/3664

**Comment by apinski-cavium** [comment]
+1 from me.

**Review by jafingerhut — APPROVED** [review]
LGTM

**Review by jafingerhut — APPROVED** [review]
LGTM

**Pull request merged**
