### PR TITLE
Addressed issue #170

### PR DESCRIPTION
**Pull request by mbudiu-vmw**

### CODE REVIEW

**Comment by jafingerhut** [comment]
@mbudiu-vmw There seem to be some automated checks that fail for this change.  You might want to run Madoko on your local copy to see if there are any errors -- perhaps an incorrect cross-ref name?

**Comment by cc10512** [comment]
It's ok to merge. The error was that the travis build was triggered for a branch other than master. We don't have checks for individual branches. Just needs rebasing noe.

**Comment by jnfoster** [comment]
[minor] The link to see the output of the Travis build is also broken... it
asks me to log in.

**Comment by jnfoster** [comment]
@mbudiu-vmw This looks good to go. Would you like to bring the branch up to date, or shall I do it?

**Pull request merged**
