### PR TITLE
Add top level file LICENSE copied from p4lang/p4c/LICENSE

### PR DESCRIPTION
**Pull request by jafingerhut**
containing the Apache 2.0 license.

### CODE REVIEW

**Comment by jafingerhut** [comment]
This is one possible way to address #918 - Add a top level file LICENSE to this repository that contains the Apache 2.0 license.  @jnfoster plans to review the question of the license for the P4_16 language specification by the TST, so this should not be merged in unless that group approves of this plan.

**Review by mbudiu-vmw — APPROVED** [review]
What does this license apply to?
Spec? PSA spec? Source files?
Shouldn't we use a contents license?
https://en.wikipedia.org/wiki/List_of_free-content_licences

**Comment by jafingerhut** [comment]
The same thing it applies to in this repository :-).  https://github.com/p4lang/p4runtime

In other words, I don't know.  One interpretation is it applies to every file in the repository.  As I mentioned in my comment above, Nate has taken the action item to decide whether some of the files, e.g. documentation, might better be distributed under a different license than Apache.  By this PR, I am not trying to make this decision unilaterally.  This PR can be closed if P4.org decides that some other changes should be made instead.

**Comment by jfingerh** [comment]
@jnfoster @mbudiu-vmw Just a brief reminder of this issue.  I do not know the answers to Mihai's questions in a comment above about what license SHOULD be used for p4.org specifications, but if Apache 2.0 is what we want, then adding a LICENSE file to this repo is at least one way to go about making that explicit.  I am happy to add notes to the README pointing at this license file, and explaining which files it applies to, and which it does not, but it seems to me that it would be reasonable to apply Apache 2.0 to ALL files in this repo, documentation and code alike.  If we think specs and documentation should be under a different license than Apache 2.0, then who decides that, and how?

**Comment by jnfoster** [comment]
@bocon13 was going to check with past contributors about this. Brian, are we clear to add a license? 

If so, I think Apache2 is best for uniformity with other p4lang projects, even considering the comments on Creative Commons licenses.

**Comment by bocon13** [comment]
@jnfoster @jafingerhut, we notified all contributors last year about adding the Apache 2.0 license. There were no objections. **So, we are clear to add the license file to the repo.**

Under extremely conservative circumstances, we would need an explicit statement from each contributor. However, the P4 membership agreement clearly states that work contributed is intended to be open sourced with a permissive license:

> WHERAS, the Consortium intends to make P4 available to the public through a permissive open source license such as Apache 2.0 or BSD other substantially equivalent license;

It also included the Apache CLA, which provides that contributions are effectively licensed under the terms of the Apache 2.0 license.

Therefore, we've decided that a notification about the new license with the opportunity to object would be sufficient.

---

Regarding the question on which files to license, I think that the easiest thing to do here is to just license everything under Apache 2.0. It's a well understood license that is widely used in the P4 (and more broadly) ONF ecosystem. It covers copyright and patents. It also avoid the question of how to use code snippets that are contained in the spec docs. Technically, there may be a better license for the spec, but Apache 2.0 seems good enough.

**Review by bocon13 — APPROVED** [review]

**Comment by jnfoster** [comment]
Thanks @bocon13 and @jfingerh!

**Pull request merged**
