### PR TITLE
Add explanation why there is no packet length field in PSA

### PR DESCRIPTION
**Pull request by jafingerhut**

### CODE REVIEW

**Comment by jafingerhut** [comment]
FYI @konne88

**Review by vgurevich — APPROVED** [review]

**Comment by konne88** [comment]
looks good to me

**Comment by stefanheule** [comment]
Looks good to me.

**Review by gbrebner — APPROVED** [review]
Okay with me,

**Comment by jafingerhut** [comment]
Thanks for checking this over and the positive acknowledgement.  Merging in this "change".

**Pull request merged**
