### PR TITLE
Add semantics of assignments between header unions, and isValid()

### PR DESCRIPTION
**Pull request by jafingerhut**

### CODE REVIEW

**Comment by jafingerhut** [comment]
Not sure if this requires a wider audience for review, given that it could be considered more than just an editorial change.

**Comment by mbudiu-vmw** [comment]
The semantics is the expected one: Copy all fields. So the explanation can be short.

**Comment by jnfoster** [comment]
I agree with @mbudiu-vmw and I believe this was discussed. It just didn't
make it into the document.

To be safe, we could email p4-design but maybe that's overkill. What do you
think?

N

**Comment by jafingerhut** [comment]
I suppose the description of header union assignment could be even shorter than what I wrote.  Given that `u = hi` has perhaps-surprising no-op behavior if `hi` is invalid and `u.hj` is valid for a different member header of `u`, it seemed wise to be explicit that this is not the case for assignments between header union variables.

**Comment by jnfoster** [comment]
Looks great. Thanks Andy!

**Comment by jnfoster** [comment]
@jafingerhut, I agree with @mbudiu-vmw. Want to add one more sentence at the beginning, then let's merge?

**Comment by jafingerhut** [comment]
@jafingerhut @mbudiu-vmw I think it should be as you suggest now.  Take a look.

**Comment by mbudiu-vmw** [comment]
Looks good.

**Pull request merged**
