### PR TITLE
Compile time size determination edit

### PR DESCRIPTION
**Pull request by pataei**
Adds lists to compile time size determination.

### CODE REVIEW

**Comment by apinski-cavium** [comment]
list has only one type for its field.
I think list should error out for minSizeInBits/maxSizeInBits because there are only list literals except for passing to externs. You cannot do anything else with them.

**Comment by jnfoster** [comment]
Another perspective: because lists can be assigned to tuples, headers, and structs (Section 8.12) it could be argued that they should also support compile-time size calculations just like values of those types do.

**Comment by mbudiu-vmw** [comment]
These are not tuple expressions, they are the new lists.
This does not work in the compiler at this point.
This would only work for list literals. We don't have any other lists currently, but this could change.

**Comment by jnfoster** [comment]
Oops! Mea culpa. I was reading v1.2.3 (where what we now call lists are really tuples) and not the working draft. You're right.

**Review by jafingerhut — APPROVED** [review]
LGTM

**Comment by mbudiu-vmw** [comment]
I will close this one, I think we agreed in the design group that this feature for the list<> type is premature.

**Pull request closed without merging**
