### PR TITLE
P4_16: Clarify the operations supported on values of type varbit

### PR DESCRIPTION
**Pull request by jafingerhut**
Also correct the cross-reference that was to section

### CODE REVIEW

**Comment by jafingerhut** [comment]
One way to resolve issue https://github.com/p4lang/p4-spec/issues/733 if the option (b) described in that issue was the original intent, as I am currently guessing.

**Comment by jafingerhut** [comment]
I will leave it up to Nate and Mihai what steps they wish to take to decide whether this proposed change is merged in, but thanks for reading it over, Han, and reporting the potential confusion.

**Comment by jnfoster** [comment]
Cheers. We should briefly chat about this at an LWDG meeting.

**Comment by mbudiu-vmw** [comment]
I will merge this, since I don't think it is controversial.

**Pull request merged**
