### PR TITLE
Make grammar.mdk file more similar to p4c's grammar

### PR DESCRIPTION
**Pull request by jfingerh**
This makes it easier to compare the two grammars using simple tools like diff.

### CODE REVIEW

**Comment by jfingerh** [comment]
It may make these changes easier to review if you examine the changes as I originally made them in several smaller steps, as described here: https://github.com/jafingerhut/p4-guide/tree/master/compare-p4c-grammar-with-spec

**Review by mbudiu-vmw — APPROVED** [review]

**Comment by apinski-cavium** [comment]
+1 from me:
I looked over it to make sure there was no functional changes and only style changes in there.

**Comment by jafingerhut** [comment]
@mbudiu-vmw Do you want other reviews before merging this in?

No matter when something like this is merged in, it is likely to cause some amount of updates required in other outstanding PRs that update the grammar.mdk file, but except for that, I cannot think of any reason to delay this PR.

If there is concern with the difficulty of merging other PRs that also change the grammar.mdk file, I would not mind helping update a handful of them (certainly my own I will update).

**Comment by mbudiu-vmw** [comment]
I am fine

**Comment by jfingerh** [comment]
OK, I will go ahead and merge this in.  If anyone has difficulty merging their PRs that modify grammar.mdk after this is merged in, please point them my way for help or advice.

**Pull request merged**
