### PR TITLE
Add match_kind optional to PSA specification

### PR DESCRIPTION
**Pull request by jafingerhut**

### CODE REVIEW

**Review by jnfoster — APPROVED** [review]
Looks good!

**Review by mbudiu-vmw — APPROVED** [review]

**Comment by konne88** [comment]
Do we also have to update this file?
https://github.com/p4lang/p4c/blob/master/p4include/psa.p4#L400

**Comment by jafingerhut** [comment]
@konne88 To support this in p4c, yes that psa.p4 include file would need to be updated, too.

**Comment by konne88** [comment]
Thanks Andy. Once we add it to the p4c include file, do you know if it would it just work, or would we also have to change the compiler? 

Would we submit this PR first, and then send the followup PR to the p4c repo?

**Comment by jafingerhut** [comment]
I think submitting it for the p4c compiler would be reasonable now, perhaps with a note that it is probably best to wait for this PR to be merged before merging that one.

There is only an incomplete open source p4c back end that supports the PSA architecture for behavioral-model (a process called psa_switch, instead of simple_switch) today, and it fails to support so many other PSA features that if it fails to support match_kind optional for a while longer, I don't think anyone will notice.  PSA architecture implementations for other targets may very well beat that one to completion. (help welcome on the BMv2 PSA support, if you know of anyone interested)

**Comment by jafingerhut** [comment]
There was discussion of this topic in the P4 LDWG meeting early April, with no objections for adding this to the PSA.  There was discussion of what a prerequisite might be for adding match_kind `optional` to core.p4, i.e. the base language specification, but that can be more fully discussed later.  Adding this to PSA now is useful and desirable.

**Pull request merged**
