### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by mary-grace**
hi Nate - I've been working with the ONF team on a variety of projects, including standardizing the onboarding process for their platforms & projects. Making sure that the Code of Conduct is promoted is one of the processes that we're implementing for all ONF projects, including P4. Let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jnfoster** [comment]
Sounds good. Should this perhaps go in p4lang/governance?

**Comment by mary-grace** [comment]
That sounds like a good idea -- thanks for the suggestion! Would you like me to resubmit the PR? Or will you simply move it over to the correct place?

**Comment by jnfoster** [comment]
I don't believe PRs can be moved across repositories with Git. So please recreate it there.

Thanks!

**Comment by jnfoster** [comment]
``

**Comment by jnfoster** [comment]
Actually, upon further review, I think having this short notice here is good. Maybe we can put the full text under governance?

**Comment by mary-grace** [comment]
Awesome - thanks @jnfoster! The thought was that if we keep the notice short on the Github repos rather than posting the full Code of Conduct, that allows for minor changes down the road without duplicating efforts to update it on all the various sites.

**Comment by mary-grace** [comment]
I clicked over to the governance repo but given that it's an empty repo, I can't fork it in order to submit a PR.

**Pull request merged**
